name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: user-app
            dockerfile: ./docker/Dockerfile.user
          - image: bank-webhook
            dockerfile: ./docker/Dockerfile.bank

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: udaybhole/zappay:${{ matrix.image }}-latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull udaybhole/zappay:${{ matrix.image }}-latest
          sudo docker stop zappay-${{ matrix.image }} || true
          sudo docker rm zappay-${{ matrix.image }} || true
          sudo docker run -d --name zappay-${{ matrix.image }} -p 3005:3000 udaybhole/zappay:${{ matrix.image }}-latest