name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    
    - name: Run Database Migrations
      run: |
        npm install -g prisma
        prisma migrate deploy
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile.user ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: udaybhole/zappay:user-app-latest

    - name: Verify Pushed Image
      run: docker pull udaybhole/zappay:user-app-latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull udaybhole/zappay:user-app-latest
            sudo docker stop zappay || true
            sudo docker rm zappay || true
            sudo docker run -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                            -e NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} \
                            -d --name zappay --restart unless-stopped -p 3005:3001 udaybhole/zappay:user-app-latest